plugins {
    id 'com.android.application'
}

android {
    namespace 'com.sajad.tankhahyar'
    compileSdk 34

    defaultConfig {
        applicationId 'com.sajad.tankhahyar'
        minSdk 24
        targetSdk 34
        versionCode 5
        versionName '1.4'
    }

    signingConfigs {
        release {
            storeFile file('tankhahyar.jks')
            storePassword 'tankhahyar1405'
            keyAlias 'tankhahyar'
            keyPassword 'tankhahyar1405'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.11.0'
    implementation 'androidx.core:core:1.13.1'
}
